const ROLE_PLAYER = "PLAYER";
const ROLE_RECRUITER = "RECRUITER";
const ROLE_ADMIN = "ADMIN";
const HIDDEN_CONVERSATIONS_STORAGE_KEY = "cc.hiddenConversations";
const BULK_LOOKUP_THRESHOLD = 2;
const COLLECTION_CACHE_TTL_MS = 12_000;

export {
  BULK_LOOKUP_THRESHOLD,
  COLLECTION_CACHE_TTL_MS,
  HIDDEN_CONVERSATIONS_STORAGE_KEY,
  ROLE_ADMIN,
  ROLE_PLAYER,
  ROLE_RECRUITER,
};
